# Analise de data/raw/colaboradores.csv

In [1]:
import os
import pandas as pd

In [5]:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('.')))))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DIR = os.path.join(DATA_DIR, 'raw')

In [7]:
df = pd.read_csv(os.path.join(RAW_DIR, 'colaboradores.csv'))
df.shape

(60, 7)

In [8]:
df.head()

,id_colaborador,nome,departamento,cargo,data_admissao,salario,status
0,1001,Ana Paula Silva,TI,Assistente,2022-01-10,2100,Ativo
1,1002,Bruno Henrique Costa,Compras,Assistente,2022-02-07,1850,Férias
2,1003,Camila Oliveira Santos,Comercial,Auxiliar,2022-03-08,4500,Ativo
3,1004,Daniel Almeida,TI,Assistente,2022-04-05,3800,Ativo
4,1005,Eduardo Martins,Recursos Humanos,Coordenador,2022-05-04,3800,Ativo

In [9]:
df.tail()

,id_colaborador,nome,departamento,cargo,data_admissao,salario,status
55,1056,Samuel Rocha,TI,Assistente,2026-04-27,3800,Ativo
56,1057,Taina Lopes,Financeiro,Auxiliar,2026-05-26,2300,Ativo
57,1058,Vitor Hugo,Compras,Analista,2026-06-23,2300,Ativo
58,1059,Yasmin Alves,Administrativo,Auxiliar,2026-07-22,3200,Férias
59,1060,Wesley Martins,Compras,Analista,2026-08-20,2500,Ativo

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_colaborador  60 non-null     int64
 1   nome            60 non-null     str
 2   departamento    60 non-null     str
 3   cargo           60 non-null     str
 4   data_admissao   60 non-null     str
 5   salario         60 non-null     int64
 6   status          60 non-null     str
dtypes: int64(2), str(5)
memory usage: 3.4 KB

In [17]:
df.duplicated().sum()

np.int64(0)