# Analise de data/raw/contas_pagar.csv

In [1]:
import os
import pandas as pd

In [2]:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('.')))))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DIR = os.path.join(DATA_DIR, 'raw')

In [3]:
df = pd.read_csv(os.path.join(RAW_DIR, 'contas_pagar.csv'))
df.shape

(180, 9)

In [4]:
df.head()

,id_conta,data_emissao,data_vencimento,id_fornecedor,descricao,categoria,valor,status,responsavel
0,5001,2026-01-02,2026-01-09,2010,Compra de alimentos,Serviços,1600.35,Pago,Vinicius Castro
1,5002,2026-01-03,2026-02-02,2018,Conta de energia,Infraestrutura,4221.02,Pago,Karen Freitas
2,5003,2026-01-04,2026-01-19,2013,Serviço contábil,Infraestrutura,1265.06,Aprovacao,Igor Mendes
3,5004,2026-01-05,2026-02-19,2005,Serviço de limpeza,Tecnologia,1292.94,Aprovacao,Wesley Martins
4,5005,2026-01-07,2026-01-22,2001,Serviço de internet,Administrativo,3860.91,Pendente,Rodrigo Tavares

In [5]:
df.tail()

,id_conta,data_emissao,data_vencimento,id_fornecedor,descricao,categoria,valor,status,responsavel
175,5176,2026-08-19,2026-09-09,2012,Serviço de limpeza,Infraestrutura,1080.69,Aprovacao,Priscila Monteiro
176,5177,2026-08-21,2026-09-18,2019,Material de informática,Administrativo,11297.09,Cancelado,Rodrigo Tavares
177,5178,2026-08-22,2026-09-06,2010,Material de escritório,Tecnologia,5104.67,Aprovacao,Priscila Monteiro
178,5179,2026-08-23,2026-09-13,2009,Serviço de internet,Serviços,7049.34,Pendente,Diego Fernandes
179,5180,2026-08-25,2026-09-24,2005,Conta de energia,Infraestrutura,11044.67,Pendente,Felipe Cunha

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_conta         180 non-null    int64
 1   data_emissao     180 non-null    str
 2   data_vencimento  180 non-null    str
 3   id_fornecedor    180 non-null    int64
 4   descricao        180 non-null    str
 5   categoria        180 non-null    str
 6   valor            180 non-null    float64
 7   status           180 non-null    str
 8   responsavel      180 non-null    str
dtypes: float64(1), int64(2), str(6)
memory usage: 12.8 KB

In [7]:
df.duplicated().sum()

np.int64(0)