# Analise de data/raw/fornecedores.csv

In [1]:
import os
import pandas as pd

In [2]:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('.')))))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DIR = os.path.join(DATA_DIR, 'raw')

In [3]:
df = pd.read_csv(os.path.join(RAW_DIR, 'fornecedores.csv'))
df.shape

(20, 6)

In [4]:
df.head()

,id_fornecedor,fornecedor,categoria,cidade,prazo_pagamento_dias,status
0,2001,Papelaria Central,Transporte,Álvares Machado,28,Ativo
1,2002,Office Solutions,Limpeza,Santo Anastácio,7,Ativo
2,2003,Limpeza Ideal,Limpeza,Álvares Machado,7,Ativo
3,2004,Tecno Sistemas,Material Escritório,Regente Feijó,15,Inativo
4,2005,Transportes Paulista,Alimentação,Álvares Machado,45,Ativo

In [5]:
df.tail()

,id_fornecedor,fornecedor,categoria,cidade,prazo_pagamento_dias,status
15,2016,Correios Empresarial,Alimentação,Álvares Machado,45,Ativo
16,2017,RH Consultoria,Serviços,Regente Feijó,28,Inativo
17,2018,Marketing Criativo,Limpeza,Santo Anastácio,30,Ativo
18,2019,Software Cloud,Transporte,Presidente Prudente,30,Ativo
19,2020,Alimentos Bom Sabor,Transporte,Álvares Machado,21,Ativo

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_fornecedor         20 non-null     int64
 1   fornecedor            20 non-null     str
 2   categoria             20 non-null     str
 3   cidade                20 non-null     str
 4   prazo_pagamento_dias  20 non-null     int64
 5   status                20 non-null     str
dtypes: int64(2), str(4)
memory usage: 1.1 KB

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

       id_fornecedor  prazo_pagamento_dias
count       20.00000             20.000000
mean      2010.50000             21.350000
std          5.91608             11.877777
min       2001.00000              7.000000
25%       2005.75000             13.000000
50%       2010.50000             21.000000
75%       2015.25000             28.000000
max       2020.00000             45.000000

In [10]:
df.columns

Index(['id_fornecedor', 'fornecedor', 'categoria', 'cidade',
       'prazo_pagamento_dias', 'status'],
      dtype='str')