# Analise de data/raw/movimentacoes_caixa

In [1]:
import os
import pandas as pd

In [2]:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('.')))))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DIR = os.path.join(DATA_DIR, 'raw')

In [3]:
df = pd.read_csv(os.path.join(RAW_DIR, 'movimentacoes_caixa.csv'))
df.shape

(220, 7)

In [4]:
df.head()

,id_movimentacao,data,tipo,categoria,descricao,valor,responsavel
0,9001,2026-01-02,Saida,Impostos,Compra material,14583.18,Raquel Mendes
1,9002,2026-01-03,Saida,Folha,Conta de energia,3504.45,Juliana Barbosa
2,9003,2026-01-04,Saida,Aluguel,Pagamento fornecedor,14664.04,Gisele Moraes
3,9004,2026-01-05,Entrada,Aluguel,Folha salarial,8025.50,Carlos Eduardo
4,9005,2026-01-06,Saida,Fornecedores,Conta de energia,2123.26,Aline Pereira

In [5]:
df.tail()

,id_movimentacao,data,tipo,categoria,descricao,valor,responsavel
215,9216,2026-08-26,Saida,Vendas,Recebimento de cliente,1828.74,Renata Moreira
216,9217,2026-08-27,Entrada,Energia,Licença software,730.15,Yasmin Alves
217,9218,2026-08-28,Entrada,Impostos,Pagamento imposto,8512.97,Fabio Correia
218,9219,2026-08-29,Saida,Impostos,Recebimento de cliente,13959.55,Caio Ribeiro
219,9220,2026-08-31,Saida,Vendas,Pagamento aluguel,12679.31,Gabriel Rodrigues

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_movimentacao  220 non-null    int64
 1   data             220 non-null    str
 2   tipo             220 non-null    str
 3   categoria        220 non-null    str
 4   descricao        220 non-null    str
 5   valor            220 non-null    float64
 6   responsavel      220 non-null    str
dtypes: float64(1), int64(1), str(5)
memory usage: 12.2 KB

In [9]:
df.duplicated().sum()

np.int64(0)